[workspace]
members = [
    "uniswap-v2/contracts/**",
    "farming/contracts/**",
    "nameservice/contracts/**",
#    "flipper/flipper/contracts/*" <- uncomment this if you want to use flipper
    "psp34_shiden/contracts/shiden34",
]

exclude = [
    "uniswap-v2/logics",
    "farming/logics",
]
